#!/bin/sh

os_name=`uname | lowercase`
case "${os_name}" in
    darwin*)
        pbcopy
        ;;
    linux*)
        if [[ "$(uname -r)" == *microsoft* ]]; then
            clip.exe
        else
            xsel --clipboard --input
        fi
        ;;
esac
